# Generated by Django 4.0.4 on 2022-04-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
    ]
