# Generated by Django 4.0.4 on 2022-05-24 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.org_profile_creation'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
