# Generated by Django 4.0.4 on 2022-05-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_jobpost_organization_alter_jobpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_creation',
            name='profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
