# Generated by Django 4.0.4 on 2022-05-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_user_profile_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_creation',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
