# Generated by Django 4.0.4 on 2022-05-28 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_user_profile_creation_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.org_profile_creation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user_profile_creation')),
            ],
        ),
    ]
