# Generated by Django 4.0.4 on 2022-05-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='jobpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.jobpost'),
        ),
    ]
