# Generated by Django 4.0.4 on 2022-05-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_user_profile_creation_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
