# Generated by Django 4.0.4 on 2022-05-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_proposal_jobpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='organization',
        ),
    ]
