# Generated by Django 4.0.4 on 2022-05-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_org_profile_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('INTERN', 'Internship'), ('FREELANCE', 'Freelance')], default='FT', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('WEB', 'Website & Software'), ('UI', 'UI/UX')], default='WEB', max_length=100)),
                ('description', models.TextField()),
                ('orgname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.org_profile_creation')),
            ],
        ),
    ]
