# Generated by Django 4.0.4 on 2022-05-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_jobpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='orgname',
            new_name='organization',
        ),
    ]
