# Generated by Django 4.0.4 on 2022-05-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_rename_orgname_jobpost_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='organization',
        ),
    ]
