# Generated by Django 4.0.4 on 2022-05-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_remove_jobpost_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.CharField(choices=[('Website & Software', 'Website & Software'), ('UI/UX', 'UI/UX')], default='Website & Software', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Freelance', 'Freelance')], default='Full Time', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_profile_creation',
            name='category',
            field=models.CharField(choices=[('Website & Software', 'Website & Software'), ('UI/UX', 'UI/UX')], default='Website & Software', max_length=100),
        ),
    ]
