# Generated by Django 4.0.4 on 2022-05-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_jobpost_date_created_alter_jobpost_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='org_profile_creation',
            name='jobs',
            field=models.ManyToManyField(to='API.jobpost'),
        ),
    ]
