# Generated by Django 4.0.4 on 2022-05-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_jobpost_title_org_profile_creation_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org_profile_creation',
            name='jobs',
        ),
        migrations.AddField(
            model_name='org_profile_creation',
            name='jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.jobpost'),
        ),
        migrations.AlterField(
            model_name='org_profile_creation',
            name='orgname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
