# Generated by Django 4.0.4 on 2022-05-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_remove_org_profile_creation_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_creation',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
